language: python
python:
  - 2.7
  - 3.6
  - 3.7
dist: focal
cache: pip

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git

install:
  - pip install -r requirements.txt
  - pip install flake8 pylint

script:
  # Code quality check
  - flake8 --ignore F403,F405 spynnaker_visualisers
  - ( pylint spynnaker_visualisers; exit $(($? & 35)) )
