name: Check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip, etc
      uses: ./support/actions/python-tools
    - name: Install Spinnaker Dependencies
      uses: ./support/actions/checkout-spinn-deps
      with:
        repositories: >
          SpiNNUtils SpiNNMachine SpiNNMan PACMAN DataSpecification spalloc
          SpiNNFrontEndCommon
        install: true
    - name: Setup
      uses: ./support/actions/run-setup
      with:
        test-requirements-path: .github/requirements-check.txt
    - name: Lint with flake8
      run: flake8 --ignore F403,F405 spynnaker_visualisers
    - name: Lint with pylint
      uses: ./support/actions/pylint
      with:
        package: spynnaker_visualisers
